/* tslint:disable:max-line-length */
export const PLACEHOLDER_DATA_URI =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAABGdBTUEAALGPC/xhBQAAAA1JREFUCB1jePHi5X8ACS4DuZs0+zoAAAAASUVORK5CYII=';
